# we create a Docker image from source code
version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host(laptop)}: {port in Container}
      #enviroment variables, like db's username, password,...
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: testdb
    networks: 
      - nestjs-networks
networks:
  nestjs-networks: 
#Create container, network,... from "docker compose" file:
#-d: deamon/background mode
#docker compose up -d
#if you want to start only spectified services/container:
#docker compose up -d dev-database -d